import 'package:customer_portal/model/appointments.dart';
import 'package:customer_portal/model/mobiapp.dart';
import 'package:customer_portal/model/user.dart';
import 'package:customer_portal/model/weather.dart';

class AppData {
  static final AppData _appData = AppData._internal();
  String appVersion = '1.0.0+9';

  List<StationList> stationListData = [];
  String apiWeatherKey = '95e5357aa88a0bc4d2d04fe6188b80f4';
  String apiWeatherIcon = 'https://openweathermap.org/img/wn/';
  List<WeatherModel> weatherData = [];
  List<ImageData> imageData = [];
  MobiAppData mobiAppData = MobiAppData();
  List<String> sectorList = [];
  List<ModuleData> modulesList = [];
  List<TerminalLayoutData> portLayoutsList = [];
  List<PrePlanTansactionModel> transactionData = [];
  List<GcosPortMapping> gcosPortMapping = [];
  List<FacilityItems> facilitiesList = [];
  List<LookUpData> stakeholderList = [],
      shippingLineList = [],
      stevedoreList = [],
      berthList = [],
      portList = [],
      vesselTypeList = [],
      complexQueryList = [];
  NavisSubscribeData activeNavisUser = NavisSubscribeData();
  List<NavisFacilities> navisFacilitiesList = [];
  String myPortSelection = "",
      myVesselNameSelection = "",
      myVoyageNumberSelection = "",
      myStakeholderSelection = "",
      myStevedoreSelection = "",
      myBerthSelection = "",
      myVesselTypeSelection = "",
      myShippingLineSelection = "",
      myBerthSuitability = "",
      myDischargeSequenceSelection = "",
      myLoadSequenceSelection = "",
      myVolumeCommentsSelection = "",
      myMafiListSelection = "",
      mySideRampSelection = "No",
      myPanelingTypeSelection = "Electronic",
      myJSONPayLoadSelection = "";
  bool checkboxHeavies = false,
      checkboxMafi = false,
      checkboxStatics = false,
      checkboxTracks = false,
      checkboxUsed = false,
      checkboxNewImports = false,
      checkboxNewExports = false;
  DateTime myVesselETASelection = DateTime.now(),
      myStartOperationsSelection = DateTime.now();
  int myImportNewSelection = 0,
      myExportNewSelection = 0,
      myImportRubberHeaviesSelection = 0,
      myExportRubberHeaviesSelection = 0,
      myImportUsedHeaviesSelection = 0,
      myImportStaticsNonMafiSelection = 0,
      myExportStaticsNonMafiSelection = 0,
      myImportUsedStaticsSelection = 0,
      myImportMafiWithCargoSelection = 0,
      myExportMafiWithCargoSelection = 0,
      myImportStaticsMafiSelection = 0,
      myExportStaticsMafiSelection = 0,
      myImportUsedSelection = 0,
      myExportUsedSelection = 0,
      myImportHeaviesTracksSelection = 0,
      myExportHeaviesTracksSelection = 0,
      myDirectRestowSelection = 0,
      myIndirectRestowSelection = 0,
      myStevedoreDriversSelection = 0,
      myStevedorePilotsSelection = 0,
      myExportLanesSelection = 0,
      myImportLanesSelection = 0,
      myReverseStowTimeSelection = 0,
      mySecureMainDeckSelection = 0,
      myBunkerTimeSelection = 0,
      myClearMainDeckSelection = 0,
      myBreakStowSelection = 0,
      myunlashingUnitsSelection = 0,
      myDirectRestowTimeSelection = 0,
      myIndirectRestowTimeSelection = 0,
      myPanelingTimeSelection = 0;

  List<TranshipmentModel> transhipmentPreCarrier = [],
      transhipmentOnCarrier = [];
  VesselModel vesselDetails = VesselModel(
    berthCode: "",
    vesselName: "",
    voyage: "",
    port: "",
    stakeholder: "",
    stevedore: "",
    vesselType: "",
    shippingLine: "",
    vesselETA: DateTime.now(),
    startOperations: DateTime.now(),
    endOperations: DateTime.now(),
    departureTime: DateTime.now(),
    berthSuitability: "",
  );
  VesselPreparation preparationDetails = VesselPreparation(
    paneling: "",
    clearMainDeck: 0,
    breakStow: 0,
    unlashingUnits: 0,
    directRestow: 0,
    indirectRestow: 0,
    panelingTime: 0,
  );
  VolumesModel volumeDetails = VolumesModel(
    importNew: 0,
    exportNew: 0,
    importRubberHeavies: 0,
    exportRubberHeavies: 0,
    importUsedHeavies: 0,
    importStaticsNonMafi: 0,
    exportStaticsNonMafi: 0,
    importUsedStatics: 0,
    importMafiWithCargo: 0,
    exportMafiWithCargo: 0,
    importStaticsMafi: 0,
    exportStaticsMafi: 0,
    importUsed: 0,
    exportUsed: 0,
    importHeaviesTracks: 0,
    exportHeaviesTracks: 0,
  );
  RequirementsModel requirementDetails = RequirementsModel(
    dischargeSequence: "",
    loadSequence: "",
    volumeComments: "",
    mafiList: "",
    directRestows: 0,
    indirectRestows: 0,
    stevedoreDrivers: 0,
    stevedorePilots: 0,
    exportLanes: 0,
    importLanes: 0,
    reverseStowTime: 0,
    secureMainDeck: 0,
    bunkerTime: 0,
    sideRamp: "No",
    parallelHeavies: false,
    parallelMafis: false,
    parallelStatics: false,
    parallelTracks: false,
    parallelUsed: false,
    parallelImportNew: false,
    parallelExportNew: false,
  );
  Map<String, dynamic> jsonPayload = {
    "@version": "1.0",
    "Vessel_Visit": [
      {
        "VISIT": "CTCT11555",
        "FACILITY": "CTCT",
        "LINE": "MAE",
        "VESSEL_NAME": "MAERSK CHENNAI",
        "VSL_CLASS": "1331",
        "QUAY": "4994",
        "BOLLARD_FORE": "115",
        "BOLLARD_AFT": "127",
        "IB_VYG": "518E",
        "OB_VYG": "518E",
        "PHASE": "WORKING",
        "ETA": "2025-05-17 14: 00: 00.0",
        "PETA": "2025-05-17 08: 00: 00.0",
        "ETD": "2025-05-19 18: 00: 00.0",
        "PETD": "2025-05-18 22: 00: 00.0",
        "ATA": "2025-06-04 08: 00: 00.0",
        "ATD": "2025-06-04 22: 00: 00.0",
        "BEGIN_RECEIVE": "2025-05-30 17: 59: 11.907",
        "REEFER_CUTOFF": "2025-06-03 18: 00: 00.0",
        "DRY_CUTOFF": "2025-06-02 18: 00: 00.0",
        "HAZ_CUTOFF": "2025-06-02 18: 00: 00.0",
        "OUTBOUND_UNIT_COUNT": "0",
        "OUTBOUND_LOAD_COUNT": "0",
        "INBOUND_UNIT_COUNT": "0",
        "INBOUND_DISCHARGE_COUNT": "0",
      },
      {
        "VISIT": "CTCT11567",
        "FACILITY": "CTCT",
        "LINE": "MSC",
        "VESSEL_NAME": "MSC ANCHORAGE",
        "VSL_CLASS": "1983",
        "QUAY": "14104",
        "BOLLARD_FORE": "94",
        "BOLLARD_AFT": "109",
        "IB_VYG": "NZ512A",
        "OB_VYG": "NZ518R",
        "PHASE": "WORKING",
        "ETA": "2025-05-14 18: 00: 00.0",
        "PETA": "2025-05-10 06: 00: 00.0",
        "ETD": "2025-05-16 14: 00: 00.0",
        "PETD": "2025-05-12 06: 00: 00.0",
        "ATA": "2025-05-14 18: 15: 00.0",
        "ATD": "",
        "BEGIN_RECEIVE": "2025-05-08 13: 59: 54.22",
        "REEFER_CUTOFF": "2025-05-14 06: 15: 00.0",
        "DRY_CUTOFF": "2025-05-13 06: 00: 00.0",
        "HAZ_CUTOFF": "2025-05-13 06: 00: 00.0",
        "OUTBOUND_UNIT_COUNT": "0",
        "OUTBOUND_LOAD_COUNT": "0",
        "INBOUND_UNIT_COUNT": "0",
        "INBOUND_DISCHARGE_COUNT": "0",
      },
      {
        "VISIT": "CTCT11576",
        "FACILITY": "CTCT",
        "LINE": "COS",
        "VESSEL_NAME": "COSCO IZMIR",
        "VSL_CLASS": "2303",
        "QUAY": "14105",
        "BOLLARD_FORE": "76",
        "BOLLARD_AFT": "89",
        "IB_VYG": "082W",
        "OB_VYG": "082E",
        "PHASE": "WORKING",
        "ETA": "2025-08-17 06: 00: 00.0",
        "PETA": "2025-05-14 14: 00: 00.0",
        "ETD": "2025-08-29 12: 00: 00.0",
        "PETD": "2025-05-16 22: 00: 00.0",
        "ATA": "2025-08-17 10: 00: 00.0",
        "ATD": "",
        "BEGIN_RECEIVE": "2025-05-11 17: 59: 39.623",
        "REEFER_CUTOFF": "2025-05-15 18: 00: 00.0",
        "DRY_CUTOFF": "2025-05-14 19: 00: 00.0",
        "HAZ_CUTOFF": "2025-05-14 19: 00: 00.0",
        "OUTBOUND_UNIT_COUNT": "0",
        "OUTBOUND_LOAD_COUNT": "0",
        "INBOUND_UNIT_COUNT": "0",
        "INBOUND_DISCHARGE_COUNT": "0",
      },
      {
        "VISIT": "CTCT11601",
        "FACILITY": "CTCT",
        "LINE": "MSC",
        "VESSEL_NAME": "MSC TOKATA F",
        "VSL_CLASS": "2856",
        "QUAY": "",
        "BOLLARD_FORE": "",
        "BOLLARD_AFT": "",
        "IB_VYG": "ZB422SSG",
        "OB_VYG": "ZB422SSG",
        "PHASE": "WORKING",
        "ETA": "2025-06-02 06: 00: 00.0",
        "PETA": "2025-06-02 06: 00: 00.0",
        "ETD": "2025-06-02 18: 00: 00.0",
        "PETD": "2025-06-02 18: 00: 00.0",
        "ATA": "2025-06-02 06: 00: 00.0",
        "ATD": "2025-06-02 18: 00: 00.0",
        "BEGIN_RECEIVE": "2030-05-29 09: 13: 35.827",
        "REEFER_CUTOFF": "",
        "DRY_CUTOFF": "",
        "HAZ_CUTOFF": "",
        "OUTBOUND_UNIT_COUNT": "0",
        "OUTBOUND_LOAD_COUNT": "0",
        "INBOUND_UNIT_COUNT": "0",
        "INBOUND_DISCHARGE_COUNT": "0",
      },
    ],
  };
  factory AppData() {
    return _appData;
  }
  AppData._internal();
}

final appData = AppData();
